// <auto-generated />
using System;
using Controle_de_Estoque_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Controle_de_Estoque_API.Migrations
{
    [DbContext(typeof(ControleDeEstoqueContext))]
    [Migration("20250225011702_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.CompatibilidadePeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PecaCompativelId")
                        .HasColumnType("int");

                    b.Property<int>("PecaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PecaCompativelId");

                    b.HasIndex("PecaId");

                    b.ToTable("CompatibilidadePecas");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.CompraPeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPedido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdVendedor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdVendedor");

                    b.ToTable("CompraPeca");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.ExemplarPeca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoVendedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EmEstoque")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PecaId")
                        .HasColumnType("int");

                    b.Property<double>("ValorPago")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("PecaId");

                    b.ToTable("ExemplarPeca");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.Peca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Grau_Importancia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade_Estoque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pecas");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.PecaVendida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoOS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExemplarPecaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ExemplarPecaId");

                    b.ToTable("PecaVendida");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.PecasCompradas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPecaVendedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdCompraPecas")
                        .HasColumnType("int");

                    b.Property<int>("IdExemplarPeca")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("IdCompraPecas");

                    b.HasIndex("IdExemplarPeca");

                    b.ToTable("PecasCompradas");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.CompatibilidadePeca", b =>
                {
                    b.HasOne("Controle_de_Estoque_API.Data.Models.Peca", "PecaCompativel")
                        .WithMany()
                        .HasForeignKey("PecaCompativelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Controle_de_Estoque_API.Data.Models.Peca", "Peca")
                        .WithMany("Compatibilidades")
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peca");

                    b.Navigation("PecaCompativel");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.CompraPeca", b =>
                {
                    b.HasOne("Controle_de_Estoque_API.Data.Models.Vendedor", "Vendedor")
                        .WithMany("compraPecaList")
                        .HasForeignKey("IdVendedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.ExemplarPeca", b =>
                {
                    b.HasOne("Controle_de_Estoque_API.Data.Models.Peca", "Peca")
                        .WithMany("ExemplarPecas")
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.PecaVendida", b =>
                {
                    b.HasOne("Controle_de_Estoque_API.Data.Models.ExemplarPeca", "ExemplarPeca")
                        .WithMany("PecasVendidas")
                        .HasForeignKey("ExemplarPecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExemplarPeca");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.PecasCompradas", b =>
                {
                    b.HasOne("Controle_de_Estoque_API.Data.Models.CompraPeca", "CompraPeca")
                        .WithMany()
                        .HasForeignKey("IdCompraPecas")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Controle_de_Estoque_API.Data.Models.ExemplarPeca", "ExemplarPeca")
                        .WithMany("PecasCompradas")
                        .HasForeignKey("IdExemplarPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompraPeca");

                    b.Navigation("ExemplarPeca");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.ExemplarPeca", b =>
                {
                    b.Navigation("PecasCompradas");

                    b.Navigation("PecasVendidas");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.Peca", b =>
                {
                    b.Navigation("Compatibilidades");

                    b.Navigation("ExemplarPecas");
                });

            modelBuilder.Entity("Controle_de_Estoque_API.Data.Models.Vendedor", b =>
                {
                    b.Navigation("compraPecaList");
                });
#pragma warning restore 612, 618
        }
    }
}
